// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtcxfnerjN3M1fyFIgVWzertKQrodszPc',
    appId: '1:578106824463:web:d5aba2f115f7a51d92907a',
    messagingSenderId: '578106824463',
    projectId: 'sustainable-living-e1c0a',
    authDomain: 'sustainable-living-e1c0a.firebaseapp.com',
    storageBucket: 'sustainable-living-e1c0a.firebasestorage.app',
    measurementId: 'G-5YNBS3GXX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1Z5BgPM69jUK3lKjDGVX4_6NaUFEM_s',
    appId: '1:578106824463:android:f05860ec7cba467192907a',
    messagingSenderId: '578106824463',
    projectId: 'sustainable-living-e1c0a',
    storageBucket: 'sustainable-living-e1c0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkOjjeBWlvafMnhzAaZSyYT7T-ekbSK0E',
    appId: '1:578106824463:ios:0b8ec5c6c31f702692907a',
    messagingSenderId: '578106824463',
    projectId: 'sustainable-living-e1c0a',
    storageBucket: 'sustainable-living-e1c0a.firebasestorage.app',
    iosBundleId: 'com.example.sustainableLiving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkOjjeBWlvafMnhzAaZSyYT7T-ekbSK0E',
    appId: '1:578106824463:ios:0b8ec5c6c31f702692907a',
    messagingSenderId: '578106824463',
    projectId: 'sustainable-living-e1c0a',
    storageBucket: 'sustainable-living-e1c0a.firebasestorage.app',
    iosBundleId: 'com.example.sustainableLiving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtcxfnerjN3M1fyFIgVWzertKQrodszPc',
    appId: '1:578106824463:web:a68ab9cb35983c3792907a',
    messagingSenderId: '578106824463',
    projectId: 'sustainable-living-e1c0a',
    authDomain: 'sustainable-living-e1c0a.firebaseapp.com',
    storageBucket: 'sustainable-living-e1c0a.firebasestorage.app',
    measurementId: 'G-F7EX0SH4SH',
  );
}
